let content = [
  {
    tagsStr: "react",
    tags: "react",
    id: 1,
    desc:
      "react chat app, create, update, delete, message firebase,firebase authorization,material-ui",
    demo: "https://chat-react-9a725.web.app/",
    code: "https://github.com/ionmax1311/react_chat",
    title: "React-chat-app",
    img: "./img/chat-app-img.PNG",
  },
  {
    tagsStr: "react",
    tags: "react",
    id: 2,
    desc: "portfolio, using React Hooks",
    demo: "https://ionmax1311.github.io/portfolio/build/",
    code: "https://github.com/ionmax1311/portfolio",
    title: "This portfolio",
    img: "./img/portfolio.png",
  },
  {
    tagsStr: "html/css | ajax",
    tags: ["html/css", "ajax"],
    id: 3,
    desc: "Landing page",
    demo: "https://ionmax1311.github.io/horizon/index.html",
    code: "https://github.com/ionmax1311/horizon",
    title: "Landing",
    img: "./img/horizon.png",
  },
  {
    tagsStr: "react",
    tags: ["react"],
    id: 4,
    desc: "simple todo-app,using redux, propTypes",
    demo: "https://ionmax1311.github.io/todo-app_redux/build/",
    code: "https://github.com/ionmax1311/todo-app_redux",
    title: "Todo-app-redux",
    img: "./img/todo.png",
  },
  {
    tagsStr: "html/css | ajax",
    tags: ["html/css", "ajax"],
    id: 5,
    desc: "landing page, submit form data in srm",
    demo: "https://ionmax1311.github.io/video/",
    code: "https://github.com/ionmax1311/video",
    title: "Landing page",
    img: "./img/video.png",
  },
  {
    tagsStr: "html/css",
    tags: ["html/css"],
    id: 6,
    desc: "using animation.css, gulp, svg animation",
    demo: "https://ionmax1311.github.io/graph/",
    code: "https://github.com/ionmax1311/graph",
    title: "Landing page",
    img: "./img/graph.png",
  },
  {
    tagsStr: "html/css | ajax | bootstrap",
    tags: ["html/css", "ajax", "bootstrap"],
    id: 7,
    desc: "set google data sheets,sms verification,",
    demo: "https://ionmax1311.github.io/investor/index.html",
    code: "https://github.com/ionmax1311/investor",
    title: "Landing page",
    img: "./img/investor.png",
  },
];

export default content;
